apiVersion: v1
kind: ConfigMap
metadata:
  name: dashboard-config
data:
  default.conf: |-
      server {
        listen 80;
        server_name localhost;
        root /usr/share/nginx/html;
        location / {
          index index.html index.htm;
        }
        location /health {
          return 200;
        }

      }